# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  database: prontusoft_development
  host: localhost
  pool: 5
  username: postgres
  password: well123

test:
  adapter: postgresql
  encoding: unicode
  database: prontusoft_test
  host: localhost
  pool: 5
  username: postgres
  password: well123