# postgresql version 9.x
#   gem install postgresql
#
#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  database: prontusoft_dev
  username: prontuso
  password: well153624
  host: localhost

test:
  adapter: postgresql
  database: prontusoft_test
  username: prontuso
  password: well153624
  host: localhost

production:
  adapter: postgresql
  database: prontusoft_production
  username: prontuso
  password: 
  host: localhost